// Generated by https://quicktype.io

export interface Movie {
    id:          number;
    title:       string;
    posterUrl:   string;
    backdropUrl: string;
    rating:      number;
    overview:    string;
    tagline:     string;
    budget:      number;
    revenue:     number;
    imdbUrl:     string;
    tmdbUrl:     string;
    releaseDate: string;
    runTime:     number;
    price:       number;
    casts:       Cast[];
    genres:      Genre[];
    trailers:    Trailer[];
}

export interface Cast {
    id:          number;
    name:        string;
    character:   string;
    profilePath: string;
}

export interface Genre {
    id:   number;
    name: string;
}

export interface Trailer {
    id:         number;
    name:       string;
    trailerUrl: string;
    movieId:    number;
}
